#ifndef SCOREBOARD_H
#define SCOREBOARD_H

#include<stdio.h>
#include "sh1106_graphics.h"


#define SCOREBOARD_HEADING_POS_X 10
#define SCOREBOARD_HEADING_POS_Y 20
#define SCOREBOARD_HEADING "Game Over"
#define SCOREBOARD_HEADING_SIZE 2

#define SCOREBOARD_SCORE_POS_X 32
#define SCOREBOARD_SCORE_POS_Y 35
#define SCOREBOARD_SCORE "Score"
#define SCOREBOARD_SCORE_SIZE 1

#define SCOREBOARD_BUTTON_RECT_POS_X 50
#define SCOREBOARD_BUTTON_RECT_POS_Y 45
#define SCOREBOARD_BUTTON_RECT_POS_WIDTH 40
#define SCOREBOARD_BUTTON_RECT_POS_HEIGHT 15
#define SCOREBOARD_BUTTON_STR_POS_X (SCOREBOARD_BUTTON_RECT_POS_X + 3)
#define SCOREBOARD_BUTTON_STR_POS_Y (SCOREBOARD_BUTTON_RECT_POS_Y + 8)
#define SCOREBOARD_BUTTON_SIZE 1
#define SCOREBOARD_BUTTON "Next"



void Scoreboard_render(uint16_t score);

void Scoreboard_Btn_clicked(uint16_t score);

#endif